export const MockData = [
  { version: 0, name: 'Beans - Fava Fresh', stock: 100 },
  { version: 0, name: 'Wine - Sogrape Mateus Rose', stock: 652 },
  { version: 0, name: 'Anisette - Mcguiness', stock: 699 },
  { version: 0, name: 'Nut - Hazelnut, Ground, Natural', stock: 702 },
  { version: 0, name: 'Coffee - Irish Cream', stock: 139 },
  { version: 0, name: 'Lettuce - Radicchio', stock: 524 },
  { version: 0, name: 'Wine - Ej Gallo Sierra Valley', stock: 958 },
  { version: 0, name: 'Apple - Fuji', stock: 830 },
  { version: 0, name: 'Table Cloth 81x81 White', stock: 928 },
  { version: 0, name: 'Irish Cream - Baileys', stock: 163 },
  { version: 0, name: 'Sobe - Tropical Energy', stock: 241 },
  { version: 0, name: 'Pasta - Spaghetti, Dry', stock: 470 },
  { version: 0, name: 'Cheese - Provolone', stock: 772 },
  { version: 0, name: 'Veal - Striploin', stock: 578 },
  { version: 0, name: 'Chocolate - Pistoles, Lactee, Milk', stock: 338 },
  { version: 0, name: 'French Pastries', stock: 809 },
  { version: 0, name: 'Wine - Ruffino Chianti Classico', stock: 300 },
  { version: 0, name: 'Lobster - Baby, Boiled', stock: 266 },
  { version: 0, name: 'Liqueur Banana, Ramazzotti', stock: 594 },
  { version: 0, name: 'Peach - Fresh', stock: 663 },
  { version: 0, name: 'Cheese - Gorgonzola', stock: 287 },
  { version: 0, name: 'Eggplant - Regular', stock: 402 },
]
