export const movieTypes = {
  TOGGLE_FAVOURITES: 'TOGGLE_FAVOURITES',
  TOGGLE_WATCH_LATER: ' TOGGLE_WATCH_LATER',
  SET_FAVOURITES: 'SET_FAVOURITES',
  SET_WATCH_LATER: 'SET_WATCH_LATER',
  SET_PAGE: 'SET_PAGE',
  SET_QUERY: 'SET_QUERY',
  ON_LOAD: 'ON_LOAD',
}
